require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - vendor/**/*
    - config/environments/**/*
    - bin/**/*
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*
    - lib/tasks/**/*
Metrics/LineLength:
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false  # count full line comments?
Rails/HttpPositionalArguments:
  Exclude:
    - spec/**/*
RSpec/HookArgument:
  Severity: error
RSpec/MessageExpectation:
  Enabled: false
RSpec/MultipleExpectations:
  Severity: error
RSpec/NestedGroups:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: 'braces_for_chaining'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IndentHash:
  EnforcedStyle: consistent
Style/Lambda:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/MultilineOperationIndentation:
  EnforcedStyle: aligned
Style/SpaceBeforeBlockBraces:
  Enabled: false
